---
- name: MariaDB server is running
  hosts: database_dev
  vars:
    mariadb_packages:

      - mariadb-server
      - python3-PyMySQL
    
    suppoorted_distros:
      - Suse

  tasks:
    - name: MariaDB packages are installed 
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      when: ansible_distribution in suppoorted_distros

    - name: start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true
